# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUI_CAWT_LeftArmRirSxD.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PyQt5.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PyQt5.QtWidgets import *

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(872, 547)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        Dialog.setFont(font)
        Dialog.setSizeGripEnabled(False)
        self.graphicsView = QGraphicsView(Dialog)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(10, 10, 621, 531))
        self.TitlePrediction = QLabel(Dialog)
        self.TitlePrediction.setObjectName(u"TitlePrediction")
        self.TitlePrediction.setGeometry(QRect(680, 440, 181, 31))
        sizePolicy.setHeightForWidth(self.TitlePrediction.sizePolicy().hasHeightForWidth())
        self.TitlePrediction.setSizePolicy(sizePolicy)
        font1 = QFont()
        font1.setFamily(u"Segoe UI")
        font1.setPointSize(20)
        font1.setBold(True)
        font1.setWeight(75)
        self.TitlePrediction.setFont(font1)
        self.LabelClassification = QLabel(Dialog)
        self.LabelClassification.setObjectName(u"LabelClassification")
        self.LabelClassification.setGeometry(QRect(640, 480, 231, 31))
        sizePolicy.setHeightForWidth(self.LabelClassification.sizePolicy().hasHeightForWidth())
        self.LabelClassification.setSizePolicy(sizePolicy)
        font2 = QFont()
        font2.setFamily(u"Segoe UI")
        font2.setPointSize(15)
        font2.setBold(False)
        font2.setWeight(50)
        self.LabelClassification.setFont(font2)
        self.LabelClassification.setTextFormat(Qt.PlainText)
        self.LabelClassification.setAlignment(Qt.AlignCenter)
        self.ButtonConnect = QPushButton(Dialog)
        self.ButtonConnect.setObjectName(u"ButtonConnect")
        self.ButtonConnect.setGeometry(QRect(680, 30, 141, 31))
        sizePolicy.setHeightForWidth(self.ButtonConnect.sizePolicy().hasHeightForWidth())
        self.ButtonConnect.setSizePolicy(sizePolicy)
        font3 = QFont()
        font3.setFamily(u"Segoe UI")
        font3.setPointSize(13)
        font3.setBold(True)
        font3.setUnderline(False)
        font3.setWeight(75)
        font3.setStrikeOut(False)
        font3.setKerning(True)
        self.ButtonConnect.setFont(font3)
        self.ButtonConnect.setMouseTracking(False)
        self.ButtonStart = QPushButton(Dialog)
        self.ButtonStart.setObjectName(u"ButtonStart")
        self.ButtonStart.setEnabled(False)
        self.ButtonStart.setGeometry(QRect(660, 110, 191, 31))
        sizePolicy.setHeightForWidth(self.ButtonStart.sizePolicy().hasHeightForWidth())
        self.ButtonStart.setSizePolicy(sizePolicy)
        self.ButtonStart.setFont(font3)
        self.ButtonStart.setMouseTracking(False)
        self.ButtonStop = QPushButton(Dialog)
        self.ButtonStop.setObjectName(u"ButtonStop")
        self.ButtonStop.setEnabled(False)
        self.ButtonStop.setGeometry(QRect(660, 150, 191, 31))
        sizePolicy.setHeightForWidth(self.ButtonStop.sizePolicy().hasHeightForWidth())
        self.ButtonStop.setSizePolicy(sizePolicy)
        self.ButtonStop.setFont(font3)
        self.ButtonStop.setMouseTracking(False)
        self.TitleHeartRate = QLabel(Dialog)
        self.TitleHeartRate.setObjectName(u"TitleHeartRate")
        self.TitleHeartRate.setGeometry(QRect(670, 200, 111, 31))
        sizePolicy.setHeightForWidth(self.TitleHeartRate.sizePolicy().hasHeightForWidth())
        self.TitleHeartRate.setSizePolicy(sizePolicy)
        font4 = QFont()
        font4.setFamily(u"Segoe UI")
        font4.setPointSize(12)
        font4.setBold(True)
        font4.setWeight(75)
        self.TitleHeartRate.setFont(font4)
        self.LabelHeartRate = QLabel(Dialog)
        self.LabelHeartRate.setObjectName(u"LabelHeartRate")
        self.LabelHeartRate.setGeometry(QRect(770, 190, 71, 31))
        sizePolicy.setHeightForWidth(self.LabelHeartRate.sizePolicy().hasHeightForWidth())
        self.LabelHeartRate.setSizePolicy(sizePolicy)
        font5 = QFont()
        font5.setFamily(u"Segoe UI")
        font5.setPointSize(12)
        font5.setBold(False)
        font5.setWeight(50)
        self.LabelHeartRate.setFont(font5)
        self.LabelHeartRate.setTextFormat(Qt.PlainText)
        self.LabelHeartRate.setAlignment(Qt.AlignCenter)
        self.ButtonDisconnect = QPushButton(Dialog)
        self.ButtonDisconnect.setObjectName(u"ButtonDisconnect")
        self.ButtonDisconnect.setGeometry(QRect(680, 70, 141, 31))
        sizePolicy.setHeightForWidth(self.ButtonDisconnect.sizePolicy().hasHeightForWidth())
        self.ButtonDisconnect.setSizePolicy(sizePolicy)
        self.ButtonDisconnect.setFont(font3)
        self.ButtonDisconnect.setMouseTracking(False)
        self.LabelGifHeartRate = QLabel(Dialog)
        self.LabelGifHeartRate.setObjectName(u"LabelGifHeartRate")
        self.LabelGifHeartRate.setGeometry(QRect(650, 230, 211, 31))
        sizePolicy.setHeightForWidth(self.LabelGifHeartRate.sizePolicy().hasHeightForWidth())
        self.LabelGifHeartRate.setSizePolicy(sizePolicy)
        self.LabelGifHeartRate.setFont(font5)
        self.LabelGifHeartRate.setTextFormat(Qt.PlainText)
        self.LabelGifHeartRate.setScaledContents(False)
        self.LabelGifHeartRate.setAlignment(Qt.AlignCenter)

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"CAWT GUI LSTM", None))
        self.TitlePrediction.setText(QCoreApplication.translate("Dialog", u"Prediction:", None))
        self.LabelClassification.setText("")
        self.ButtonConnect.setText(QCoreApplication.translate("Dialog", u"Connect", None))
        self.ButtonStart.setText(QCoreApplication.translate("Dialog", u"Start Streaming", None))
        self.ButtonStop.setText(QCoreApplication.translate("Dialog", u"Stop Streaming", None))
        self.TitleHeartRate.setText(QCoreApplication.translate("Dialog", u"Heart Rate:", None))
        self.LabelHeartRate.setText("")
        self.ButtonDisconnect.setText(QCoreApplication.translate("Dialog", u"Disconnect", None))
        self.LabelGifHeartRate.setText("")
    # retranslateUi

